import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AddEventModalContext from "@/components/contexts/AddEventModalContext";
import AddEvent from "@/components/AddEvent";
import ShowEventsContext from "@/components/contexts/ShowEventsContext";
import IsNewContextProvider from "@/components/contexts/IsNewContext";
import EditEventModalContext from "@/components/contexts/EditEventModalContext";
import EditEvent from "@/components/EditEvent";
import AuthContextProvider from "@/components/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
      <AuthContextProvider>
        <IsNewContextProvider>
          <ShowEventsContext>
            <EditEventModalContext>
              <AddEventModalContext>
                {children}
                <AddEvent />
                <EditEvent/>
              </AddEventModalContext>
            </EditEventModalContext>
          </ShowEventsContext>
        </IsNewContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
